src/DevCurso.Site/Models/Aluno.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevCurso.Site.Models
{
    public class Aluno
    {
        public Aluno()
        {
            Id = Guid.NewGuid();
        }

        public Guid Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public DateTime DataNascimento { get; set; }
    }
}

src/DevCurso.Site/Models/Pedido.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevCurso.Site.Models
{
    public class Pedido
    {
        public Guid Id { get; set; }

        public Pedido()
        {
            Id = Guid.NewGuid();
        }
    }
}

src/DevCurso.Site/Controllers/HomeController.cs
using DevCurso.Site.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevCurso.Site.Controllers
{
    public class HomeController : Controller
    {
        private readonly IPedidoRepository _pedidoRepository;

        public HomeController(IPedidoRepository pedidoRepository)
        {
            _pedidoRepository = pedidoRepository;
        }

        public IActionResult Index()
        {
            var pedido = _pedidoRepository.ObterPedido();
            return View();
        }
    }
}

src/DevCurso.Site/Controllers/TesteCrudController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DevCurso.Site.Data;
using DevCurso.Site.Models;
using Microsoft.AspNetCore.Mvc;

namespace DevCurso.Site.Controllers
{
    public class TesteCrudController : Controller
    {
        private readonly MeuDbContext _context;
        public TesteCrudController(MeuDbContext contexto)
        {
            _context = contexto;
        }

        public IActionResult Index()
        {
            var aluno = new Aluno
            {
                Nome = "Luiz Marcelo",
                DataNascimento = DateTime.Now,
                Email = "luiz@luiz.com"
            };

            _context.Alunos.Add(aluno);
            _context.SaveChanges();

            BuscarAluno(aluno);

            UpdateAluno(aluno);

            RemoverAluno(aluno);

            return View();
        }

        private void RemoverAluno(Aluno aluno)
        {
            _context.Alunos.Remove(aluno);
            _context.SaveChanges();
        }

        private void UpdateAluno(Aluno aluno)
        {
            aluno.Nome = "João";
            _context.Alunos.Update(aluno);
            _context.SaveChanges();
        }

        private void BuscarAluno(Aluno aluno)
        {
            var aluno2 = _context.Alunos.Find(aluno.Id);
            var aluno3 = _context.Alunos.FirstOrDefault(x => x.Email.Equals("luiz@luiz.com"));
            var aluno4 = _context.Alunos.Where(x => x.Nome == "Luiz Marcelo").ToList(); 
        }
    }
}

src/DevCurso.Site/Views/Home/Index.cshtml
Olá!

src/DevCurso.Site/Views/Shared/_Layout.cshtml
<html>
    <head>
        <title>@ViewData["Title"] - Meu App Modelo</title>

        <environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
            <link rel="stylesheet" href="~/lib/font-awesome/css/fontawesome.css" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" 
                  asp-fallback-href="~lib/bootstrap/css/bootstrap.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
                  integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" 
                  crossorigin="anonymous">
        </environment>
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppModelo</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="TesteCrud" asp-action="Index">Teste Crud</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted" style="bottom:0; width:100%; position:absolute;">
            <div class="container">Rodapé</div> 
            <br />
        </footer>


        <environment include="Development">
            <link rel="stylesheet" href="~/lib/jquery/jquery.js" />
            <link rel="stylesheet" href="~/lib/bootstrap/js/bootstrap.js" />
        </environment>
        <environment exclude="Development">
            <script src="https://code.jquery.com/jquery-migrate-3.3.2.min.js"
                    asp-fallback-src="~lib/jquery/jquery.js"
                    asp-fallback-test="window.jQuery"
                    integrity="sha256-Ap4KLoCf1rXb52q+i3p0k2vjBsmownyBTE1EqlRiMwA=" 
                    crossorigin="anonymous">
            </script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
                    asp-fallback-src="~lib/bootstrap/js/bootstrap.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
                    crossorigin="anonymous">
            </script>
        </environment>

    </body>
</html>

src/DevCurso.Site/Views/TesteCrud/Index.cshtml
Olá!